project:
  type: website
  output-dir: docs

website:
  title: "Guy Fuchs"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - text: Data Viz
        menu:
          - href: premierleague.qmd
            text: Premier League 2021â€“22
          - href: olympics.qmd
            text: Olympic Athletes and Medals 1896-2016
      - href: kidzbop.qmd
        text: Kidz Bop
      - href: project3.qmd
        text: Simulation
      - href: project4.qmd
        text: COMPAS Ethics
      - href: project5.qmd
        text: SQL Analysis of Traffic Stop Data
      - href: teamsync.qmd
        text: TeamSync Project
      - href: final_presentation.qmd
        text: Website Overview Presentation

  page-footer:
    center:
      - text: "GitHub Repo"
        href: https://github.com/gfyi1026/gfyi1026.github.io
      - text: "Email"
        href: mailto:gfyi2023@mymail.pomona.edu

format:
  html:
    theme:
      light: cerulean
      dark: cyborg
    toc: true
    page-layout: full
    css: styles.css
    mainfont: "Inter"
    sansfont: "Inter"
    monofont: "Fira Code"
    
  revealjs:
    slide-number: true
    footer: "<a href='index.html'>Back to Home</a>"
execute:
  warning: false
  message: false

editor: visual
